USE lab_mysql;
CREATE TABLE Car (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	VIN VARCHAR(255), 
	Manufacturer VARCHAR(255), 
	Model VARCHAR(255), 
	Year VARCHAR(255),
	Color VARCHAR(255)
		);
CREATE TABLE Customer (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	CustomerID INT, 
	Name VARCHAR(255), 
	PhoneNumber VARCHAR(255), 
	Email VARCHAR(255), 
	Adress VARCHAR(255), 
	City VARCHAR(255), 
	StateProvince VARCHAR(255), 
	Country VARCHAR(255), 
	ZipPostalCode INT
		);
CREATE TABLE SalesPerson (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	StaffID INT(5) ZEROFILL, 
	Name VARCHAR(255), 
	Store VARCHAR(255)
		);
CREATE TABLE Invoice (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	InvoiceID INT, 
	DateInvoices DATE, 
	ID_Car INT,
	CustomerID INT,
	StaffID INT,
	CONSTRAINT fk_Car_ID
		FOREIGN KEY (ID_Car) REFERENCES Car(ID) ON UPDATE CASCADE ON DELETE CASCADE, 
	CONSTRAINT fk_CustomerID
		FOREIGN KEY (CustomerID) REFERENCES Customer(ID) ON UPDATE CASCADE ON DELETE CASCADE, 
	CONSTRAINT fk_IStaffID		
		FOREIGN KEY (StaffID) REFERENCES SalesPerson(ID) ON UPDATE CASCADE ON DELETE CASCADE
		);
